name: Run Python
on: 
    push:
    schedule:
    - cron: 0 0 * * * #倫敦時間

jobs:
    build:
        name: run py1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run python
          run: |
            python3 test.py # test